
 package valorant_app;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
public class DatosPerfil extends javax.swing.JFrame {
  private String nombreUsuario;
    private String correoElectronico;
    FondoPanel fondo = new FondoPanel();
    /**
     * Creates new form DatosPerfil
     */
    public DatosPerfil(String nombreUsuario,String correoElectronico) {
        // Establece el nombre de usuario y correo electrónico
        this.nombreUsuario = nombreUsuario;
        this.correoElectronico = correoElectronico;

        // Crea el panel de fondo
        fondo = new FondoPanel(); // Crea una instancia del fondo
        this.setContentPane(fondo); // Establece el fondo del JFrame
        this.setLayout(new BorderLayout()); // Establece el layout del JFrame

        // Llama a initComponents después de configurar el fondo
        initComponents(); 
        this.setLocationRelativeTo(null);

        
        makeTextFieldTransparent(jTextField1);
            makeTextFieldTransparent(jTextField2);
            makeTextFieldTransparent(jTextField3);
            makeTextFieldTransparent(jTextField4);
        
        
        // Carga los datos del usuario
        loadUserData(nombreUsuario);

        // Asegúrate de que el JFrame es visible
        this.setVisible(true);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/valoLogo.png")));
        this.setTitle("Valorant Tracker");
    }
     private void makeTextFieldTransparent(javax.swing.JTextField textField) {
        textField.setBackground(new java.awt.Color(0, 0, 0, 0)); // Fondo transparente
        textField.setOpaque(false); // Asegúrate de que el JTextField no sea opaco
    }
    private void loadUserData(String nombreUsuario) {
        Query query = new Query();
        String[] userData = query.getUserData(nombreUsuario);

        if (userData != null) {
            // Cargar los datos del usuario desde la base de datos
            jTextField1.setText(userData[0]); // Nombre de usuario
            jTextField2.setText(userData[1]); // Correo electrónico
            jTextField3.setText(userData[2]); // Nivel del jugador
            jTextField4.setText(userData[3]); // Rango del jugador
        } else {
            // Usuario no encontrado
            System.out.println("Usuario no encontrado.");
            jTextField1.setText(nombreUsuario); // Mostrar el nombre de usuario
            jTextField2.setText("No disponible"); // Correo no disponible
            jTextField3.setText("1"); // Nivel por defecto para nuevos usuarios
            jTextField4.setText("Unranked"); // Establecer rango por defecto
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleBar = new javax.swing.JPanel();
        btnX = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new FondoPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        btnCambiarContrasena = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleBar.setBackground(new java.awt.Color(21, 44, 54));
        titleBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnX.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnX.setForeground(new java.awt.Color(255, 255, 255));
        btnX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnX.setText("X");
        btnX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXMouseExited(evt);
            }
        });
        titleBar.add(btnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 20, 30));

        btnMinimize.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimize.setText("-");
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });
        titleBar.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 20, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Valorant Tracker");
        titleBar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        getContentPane().add(titleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 30));

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 305));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(12, 25, 32));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 75, 180, 29));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(13, 26, 32));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 116, 155, 22));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(13, 26, 32));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 122, 22));

        jTextField4.setBackground(new java.awt.Color(13, 26, 32));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setBorder(null);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 184, 155, 22));

        btnCambiarContrasena.setBackground(new java.awt.Color(255, 68, 87));
        btnCambiarContrasena.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCambiarContrasena.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarContrasena.setText("Cambiar Contraseña");
        btnCambiarContrasena.setBorder(null);
        btnCambiarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarContrasenaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCambiarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 243, 151, 28));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nivel");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 153, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 313));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void btnCambiarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarContrasenaActionPerformed
        CambiarContrasenaFramee cambiarContrasenaFrame = new CambiarContrasenaFramee();
        cambiarContrasenaFrame.setVisible(true);
    }//GEN-LAST:event_btnCambiarContrasenaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXMouseClicked
        // TODO add your handling code here:
        //System.exit(0);
        dispose();
    }//GEN-LAST:event_btnXMouseClicked

    private void btnXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXMouseEntered
        // TODO add your handling code here:
        btnX.setForeground(new Color(255, 68, 87));
    }//GEN-LAST:event_btnXMouseEntered

    private void btnXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXMouseExited
        // TODO add your handling code here:
        btnX.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnXMouseExited

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        // TODO add your handling code here:
        btnMinimize.setForeground(new Color(255, 68, 87));
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        // TODO add your handling code here:
        btnMinimize.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnMinimizeMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarContrasena;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JLabel btnX;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel titleBar;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {
    private Image imagen;

    public FondoPanel() {
        imagen = new ImageIcon(getClass().getResource("/imagenes/fondodatoperfilf.jpg")).getImage();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Llama al método de la superclase
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this); // Dibuja la imagen ajustada al tamaño del panel
        setOpaque(false); // Configura el panel como transparente para mostrar la imagen
    }
}
}
//Listo